### ISSUE TITLE
Change RUST_LOG variable name

### ISSUE THREAD

**Issue by gdorsi44** [fermyon/feedback#15]
Hello,

Is it a possibility to consider to modify the Possibility to change RUST_LOG variable with sort of like SPIN_LOG for avoid misconfusions?

**Comment by macolso** [comment]
Thanks for reaching out, @Tudor44! Could you please open an issue at [fermyon/spin](https://github.com/fermyon/spin/issues/new) for this request? This repo is tracking feature and doc requests specific to Fermyon Cloud. Sorry for the confusion!

**Comment by gdorsi44** [comment]
> Thanks for reaching out, @Tudor44! Could you please open an issue at [fermyon/spin](https://github.com/fermyon/spin/issues/new) for this request? This repo is tracking feature and doc requests specific to Fermyon Cloud. Sorry for the confusion!

Hello @macolso thank you for clarification!

**Comment by macolso** [comment]
Of course! Don't hesitate to reach out with any questions.
