### ISSUE TITLE
Error: Build command for component gospin failed with status Exited(127)

### ISSUE THREAD

**Issue by Horiodino** [fermyon/feedback#26]
im getting this error while building the goapp in spin .
![image](https://github.com/fermyon/feedback/assets/99384392/831d98e7-8467-47b3-8597-8fe0a2d57714)

i dont know the reason , but i tried on rust and it worked .

**Comment by radu-matei** [comment]
Hi, @Horiodino!
Building Go components with Spin requires TinyGo to be installed — https://developer.fermyon.com/spin/go-components

**Comment by Horiodino** [comment]
> Hi, @Horiodino! Building Go components with Spin requires TinyGo to be installed — https://developer.fermyon.com/spin/go-components

Sorry 😅 got it. it worked in react because it's already built in it .
One more thing I would like to suggest that if any component needed to required then i would be good if it install during build ....

**Comment by Horiodino** [comment]
if user dont know ...
