### ISSUE TITLE
git repository link at the spin app view in the cloud ui

### ISSUE THREAD

**Issue by bharattech** [fermyon/feedback#28]
at https://cloud.fermyon.com/ 

I believe it would be beneficial to have git repository link at the spin app view in the cloud ui, if possible.

**Comment by macolso** [comment]
@bharattech - thanks for providing feedback. Could you elaborate on which GitHub repo you're referring to, and what sort of information would be useful?

**Comment by bharattech** [comment]
@macolso - Suppose User A has deployed n spin apps on the Fermyon cloud, each with its own corresponding Github repository. Upon logging into the cloud portal, User A is presented with a list of these spin apps. After selecting a specific spin app, a left-side view displays detailed options such as managing the domain. 

In this view, the link to the spin app's respective Github repository.

By providing the link to each spin app's Github repository, User A can conveniently manage their deployed spin apps on the Fermyon cloud.

![image](https://github.com/fermyon/feedback/assets/60472110/91aa2c72-b90d-4977-af72-0dabac3b7929)
