### ISSUE TITLE
Can't see the custom domain after add a new one.

### ISSUE THREAD

**Issue by rts-gordon** [fermyon/feedback#30]
Hi there, 
  I tested the new Domains feature, it is works. But something need improved.

 1. How to setup a https custom domain? I found that the custom domain is http, it is not a safe one.
 2. Can't see the custom domain in dashboard after add a new one, can‘t edit or remove it.

Thank you.

![image](https://github.com/fermyon/spin/assets/5645296/4c0e30b1-643d-4a01-8fe1-8d1a4f3c662e)

**Comment by itowlson** [comment]
Hi @rts-gordon I think this is a Fermyon Cloud issue rather than Spin itself.  I'll transfer the issue over.

**Comment by ingride** [comment]
hey there, thanks for reaching out. Can you provide some additional information:
- the custom domain that you tried to provision
- the steps you followed to add the domain to Fermyon Cloud
- whether or not you received an error when you clicked "save"

Please note that an SSL certificate is automatically generated as the final stage of provisioning the domain. The domain is considered live only after this stage, and at that point `http` will automatically redirect to `https`.  You can find more information and instructions on our docs: https://developer.fermyon.com/cloud/custom-domains-tutorial

**Comment by rts-gordon** [comment]
@ingride 
  Thanks for answer. It is OK now. 

  the custom domain is: empfund.org
  the steps is follow the guide: https://www.fermyon.com/blog/announcing-custom-domains
  there are no errors, no successful custom domain display when I clicked "save", and there is no SSL certificate. But after 
 one day(maybe too long), every thing is OK.

 Thank you again.

**Comment by ingride** [comment]
@rts-gordon glad to hear it. We probe ownership in an exponential backoff way so the amount of time will depend on how fast you also add the NS servers and on DNS propagating. 

Thank you again!
