### ISSUE TITLE
Discord link appears to be broken

### ISSUE THREAD

**Issue by dimitrilw** [fermyon/feedback#32]
**Describe the bug**
The Fermyon website and Github repos list `https://discord.com/invite/AAFNfS7NGf` as the Discord invite URL to use. However, it does not work; possibly expired?

**Frequency of the bug**
Please check one:
- [X] Consistent repro
- [ ] Intermittent repro
- [ ] No repro

**Set-up information**
N/A

**To Reproduce**
Visit URL.

**Expected behavior**
Valid invite code should deliver me to the Discord server's landing.

**Screenshots**
<img width="905" alt="image" src="https://github.com/fermyon/feedback/assets/5898931/82babd5b-1d39-4060-bd45-39b9601e3f39">

**Additional context**

**Comment by karthik2804** [comment]
I checked Discord and it says it is a valid link. I tested the invite on an incognito tab and it seems to work. Based on some googling around, logging out and back in may help. If that does not work, I can grab you an alternate link.

**Comment by dimitrilw** [comment]
Um.... I'll see myself out now. 😊 

That 100% fixed it. I have not experienced that before. Discord be derpy sometimes. 🤷🏻‍♂️ 

Also, if anybody else from Fermyon sees this:
Give @karthik2804 a raise. He puts up with me. That deserves a reward fo-sho.

**Comment by karthik2804** [comment]
Haha! Glad it worked out!
