### ISSUE TITLE
unable to deploy spin-hello-py

### ISSUE THREAD

**Issue by dimitrilw** [fermyon/feedback#33]
**Describe the bug**
Cannot deploy basic "hello world" python app. Repo being deployed: [spin-hello-py](https://github.com/dimitrilw/spin-hello-py)

**Frequency of the bug**
Please check one:
- [X] Consistent repro
- [ ] Intermittent repro
- [ ] No repro

**Set-up information**
spin 1.5.0 (ca08dd9 2023-09-13)
MacOS

**To Reproduce**
I am not sure this will be consistently reproducable. I can continue to get the same error with this spin app, but that does not mean it is a consistent error. At the very least, I would like to understand the error message. It is cryptic to a new spin user.

**Expected behavior**
Deploy `spin-hello-py` in the same manner that [spin-hello-rs](https://github.com/dimitrilw/spin-hello-rs) was deployed.

**Screenshots**
Pic of basic init:
<img width="771" alt="image" src="https://github.com/fermyon/feedback/assets/5898931/42916ff7-0227-4a20-ac92-05820c14a076">

`spin watch` worked fine & asset successfully served locally
<img width="578" alt="image" src="https://github.com/fermyon/feedback/assets/5898931/621d2e1a-5bda-4d2a-9c39-b938859f07a1">

`spin build` appears to work; `spin deploy` did not & error message is not clear to new spin user
<img width="728" alt="image" src="https://github.com/fermyon/feedback/assets/5898931/a3259fa9-066f-48e3-bfe9-7920db985200">

...and rerunning `spin build` & `spin deploy` -- same failure message
<img width="725" alt="image" src="https://github.com/fermyon/feedback/assets/5898931/8e2bd202-d292-4ffd-aef1-3a1ce77ce289">

**Additional context**

**Comment by karthik2804** [comment]
@dimitrilw can you try redeploying the app after deleting it from the cloud dashboard?

**Comment by dimitrilw** [comment]
will do. I was just about to add that [spin-hello-go](https://github.com/dimitrilw/spin-hello-go) deployed fine.
<img width="890" alt="image" src="https://github.com/fermyon/feedback/assets/5898931/2eaa95a9-dc0c-453c-a485-cf3bb1b508f0">

Give me a couple minutes & I will report back re results after deleting app from cloud dashboard.

**Comment by dimitrilw** [comment]
🎯 Bullseye!

@karthik2804 , you're awesome. 😄 

<img width="637" alt="image" src="https://github.com/fermyon/feedback/assets/5898931/5cd1b135-3160-4da3-b6fd-916a03a2f953">


...so I suppose this issue has morphed into something like:
Can we update [the FAQ](https://developer.fermyon.com/cloud/faq), which is ref'd in the terminal error output, to include a tip to delete cloud app & redeploy? That tip could help you all avoid others pinging with similar issue.

Closing this issue as re-deploy worked. But you all might want an internal documentation issue.

**Comment by karthik2804** [comment]
@dimitrilw glad to hear it. We will work on adding it to the documentation!

**Comment by tpmccallum** [comment]
Thanks @dimitrilw documentation has been updated https://github.com/fermyon/developer/pull/906

**Comment by dimitrilw** [comment]
Awesome! I haven't actually *done* much with the tools (yet), but what I'm seeing, I'm loving. Especially this kind of positive community culture. Whenever I get down-under && back to India, I'm getting each of you a ~~beer~~ beverage-of-choice.
