### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by ranglang** [fermyon/feedback#43]
**Describe the bug**

**Frequency of the bug**
Please check one:
- [ ] Consistent repro
- [ ] Intermittent repro
- [ ] No repro

**Set-up information**
Please share the version of Spin used when the bug occurred. You can find the version of Spin by running `spin -V`.

**To Reproduce**

**Expected behavior**

**Screenshots**
(Remember to remove any personally-identifiable information.)

![image](https://github.com/fermyon/feedback/assets/12862508/3cf633b7-5c02-483d-bce4-e4cf12d6a009)

**Additional context**

**Comment by itowlson** [comment]
Per the message, some API endpoints have been retired and you will need to update to a more recent client:

* If you are on Spin 1.2 or earlier, you will need to upgrade to Spin 1.3 or later, then install the `cloud` plugin (`spin plugins update && spin plugins install cloud`)
* If you are on Spin 1.3 or later, you will need to update the `cloud` plugin (`spin plugins update && spin plugins upgrade cloud`)

If you still run into problems with a recent `cloud` plugin, please let us know!
