### ISSUE TITLE
Python http example is working locally but  giving "Internal Server Error" on cloud deploy

### ISSUE THREAD

**Issue by farooqhasny** [fermyon/feedback#51]
**Describe the bug**

**Frequency of the bug**
Please check one:
- [x ] Consistent repro
- [ ] Intermittent repro
- [ ] No repro

**Set-up information**
spin 2.4.2 (340378e 2024-04-03)
tried on windows and WSL2 Ubuntu
**To Reproduce**
1. use https://github.com/fermyon/spin-python-sdk/tree/main/templates/http-py template to create project .
2. build and deploy on cloud once uploaded open url in browser (chrome)

**Expected behavior**
expect to see "Hello from Python!"
but getting
Internal Server Error

**Comment by mikkelhegn** [comment]
Thanks for reporting this @farooqhasny.

Could you try using this template instead? https://github.com/fermyon/spin-python-sdk/tree/v2.0/templates/http-py 

`spin template upgrade --repo https://github.com/fermyon/spin-python-sdk --branch v2.0` would be the command to use.

We believe there's an incompatibility with version `3.0.0` and `3.1.0` of the Python SDK and cloud, which we need to handle.

**Comment by farooqhasny** [comment]
Thanks for your response @mikkelhegn 
I have tried upgrading template without any success .I am attaching the project for your reference .

[http-py.zip](https://github.com/fermyon/feedback/files/14999385/http-py.zip)

**Comment by mikkelhegn** [comment]
The `spin template upgrade` command only applies to the template you use for creationg a new application, so it will not make any changes to the ones you've already created.

The main thing is the SDK and componentize-py version you're using. I'm not sure if changing the version in the `requirmens.txt` file to the below will work, but you can try.

```
spin-sdk == 2.0.0
componentize-py == 0.11.2
```

**Comment by farooqhasny** [comment]
hi @mikkelhegn 
when i try using 
spin-sdk == 2.0.0
componentize-py == 0.11.2
Python 3.10.12
and template  from https://github.com/fermyon/spin-python-sdk --branch v2.0
build fails
```
ASF1KMF:~/hello-world$ spin build
Building component hello-world with `componentize-py -w spin-http componentize app -o app.wasm`
Traceback (most recent call last):
  File "/usr/local/bin/componentize-py", line 8, in <module>
    sys.exit(script())
AssertionError: Traceback (most recent call last):
  File "/0/app.py", line 1, in <module>
    from spin_sdk.http import IncomingHandler, Request, Response
  File "/1/spin_sdk/http/__init__.py", line 5, in <module>
    from spin_sdk.http import poll_loop
  File "/1/spin_sdk/http/poll_loop.py", line 17, in <module>
    from spin_sdk.wit.imports.streams import StreamError_Closed, InputStream
ImportError: cannot import name 'StreamError_Closed' from 'spin_sdk.wit.imports.streams' (/1/spin_sdk/wit/imports/streams.py). Did you mean: 'StreamErrorClosed'?


Caused by:
    ImportError: cannot import name 'StreamError_Closed' from 'spin_sdk.wit.imports.streams' (/1/spin_sdk/wit/imports/streams.py)
Error: Build command for component hello-world failed with status Exited(1)
```

**Comment by mikkelhegn** [comment]
Do you have a repo or gist you can share?

This is my repro: https://gist.github.com/mikkelhegn/346bbff92ae9bdb2b09fd6c2948b40c5

I'm using Python 3.12.2

**Comment by farooqhasny** [comment]
i have tried compiling your gist and got this error
`ESKTOP-ASF1KMF:~/pygist$ spin build
Building component python with `componentize-py -w spin-http componentize app -o app.wasm`
Traceback (most recent call last):
  File "/home/farooq/.local/bin/componentize-py", line 8, in <module>
    sys.exit(script())
AssertionError: Traceback (most recent call last):
  File "/0/app.py", line 1, in <module>
    from spin_sdk.http import IncomingHandler, Request, Response
  File "/1/spin_sdk/http/__init__.py", line 5, in <module>
    from spin_sdk.http import poll_loop
  File "/1/spin_sdk/http/poll_loop.py", line 17, in <module>
    from spin_sdk.wit.imports.streams import StreamError_Closed, InputStream
ImportError: cannot import name 'StreamError_Closed' from 'spin_sdk.wit.imports.streams' (/1/spin_sdk/wit/imports/streams.py). Did you mean: 'StreamErrorClosed'?


Caused by:
    ImportError: cannot import name 'StreamError_Closed' from 'spin_sdk.wit.imports.streams' (/1/spin_sdk/wit/imports/streams.py)
Error: Build command for component python failed with status Exited(1)
`

**Comment by mikkelhegn** [comment]
Ok - I think we have to call @dicej to help with some debugging here... Joel?

**Comment by dicej** [comment]
@farooqhasny Based on the error message you posted, it looks like you're still using `spin-sdk` 3.0.0 rather than `spin-sdk` 2.0.0 as specified in Mikkel's gist.  Did you run `pip install -r requirements.txt`?

FWIW, I just tried the code in Mikkel's gist, and it worked for me.

**Comment by farooqhasny** [comment]
Thanks @dicej 
my apps which were create and deployed 4 days ago, which weren't working before , have start working now. seems like some recent update of spin cloud runtime has fix the issue . 
Thanks for all your support .
